# Generated by Django 4.1.3 on 2022-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svw_firebaseid', models.CharField(max_length=100)),
                ('svw_name', models.CharField(max_length=100)),
                ('svw_email', models.CharField(max_length=100, unique=True)),
                ('svw_updatedOn', models.DateTimeField(auto_now=True)),
                ('svw_userCreatedOn', models.DateTimeField(auto_now_add=True)),
                ('svw_photoUrl', models.CharField(default='NA', max_length=500)),
                ('svw_isdeleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
