# Generated by Django 4.1.3 on 2022-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svwusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='svw_bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='svw_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
