# Generated by Django 4.1.3 on 2022-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svwusers', '0002_user_svw_bio_user_svw_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='svw_address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
