# Generated by Django 4.1.3 on 2022-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svwusers', '0003_user_svw_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='svw_telephone',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
