# Generated by Django 4.1.3 on 2022-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svwusers', '0004_user_svw_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='svw_telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
