# Generated by Django 4.1.3 on 2022-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svwusers', '0005_alter_user_svw_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='svw_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='svw_postalcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='svw_province',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='svw_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='svw_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
