# Generated by Django 4.1.3 on 2022-11-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svwusers', '0006_user_svw_city_user_svw_postalcode_user_svw_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='svw_dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
