# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ 'main' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  jobid: ${GITHUB_JOB}
  workspace: ${GITHUB_WORKSPACE}
  branch: ${GITHUB_REF##*/}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
          
      - name: login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: '${{ secrets.GCP_CREDS }}'
        
      - name: Adding gcp registry secret to env (for docker access)
        run:  echo "GCP_REGISTRY=${{secrets.GCP_REGISTRY}}" >> $GITHUB_ENV
        
      - name: Build backend docker image
        run: cd backend/silverware && docker build -t ${{ env.GCP_REGISTRY }}/silverware-369717/silverware/backend:latest .
      
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
          
      - name: login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: '${{ secrets.GCP_CREDS }}'
        
      - name: Adding gcp registry secret to env (for docker access)
        run:  echo "GCP_REGISTRY=${{secrets.GCP_REGISTRY}}" >> $GITHUB_ENV
        
      - name: Build backend docker image
        run: cd frontend/frontend && docker build -t ${{ env.GCP_REGISTRY }}/silverware-369717/silverware/frontend:latest .

